### ISSUE TITLE
Error when using the EC2 deployment

### ISSUE THREAD

**Issue by ruggero-balteri** [awslabs/aws-greengrass-provisioner#303]
When executing 
`./ggp.sh -g test1 -a ARM64 -d deployments/<func-name>.conf --script --ec2-launch AmazonLinux2`
I get the following error:

`[ERROR] BasicIoHelper: Instance never became available [Authentication error occurred, the SSH key may be missing or incorrect. Giving up.]
[ERROR] BasicThreadHelper: Task exception [com.awslabs.aws.greengrass.provisioner.data.exceptions.SshRecoverableException: Authentication error occurred, the SSH key may be missing or incorrect. Giving up.]
[ERROR] AwsGreengrassProvisioner: Failed to connect and bootstrap the instance via SSH
java.lang.RuntimeException: Failed to connect and bootstrap the instance via SSH
	at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicDeploymentHelper.attemptBootstrap(BasicDeploymentHelper.java:990)
	at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicDeploymentHelper.execute(BasicDeploymentHelper.java:943)
	at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicDeploymentHelper.execute(BasicDeploymentHelper.java:62)
	at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.executeOrDisplayHelp(Operation.java:33)
	at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.lambda$execute$1(Operation.java:21)
	at io.vavr.control.Try.onSuccess(Try.java:712)
	at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.execute(Operation.java:21)
[ERROR] AwsGreengrassProvisioner: Failed to connect and bootstrap the instance via SSH
	at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$null$2(AwsGreengrassProvisioner.java:86)
	at java.util.Optional.map(Optional.java:215)
	at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$run$da6d192b$1(AwsGreengrassProvisioner.java:86)
	at io.vavr.control.Try.of(Try.java:75)
	at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.run(AwsGreengrassProvisioner.java:81)
	at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.runProvisioner(AwsGreengrassProvisioner.java:59)
	at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$main$249538b4$1(AwsGreengrassProvisioner.java:31)
	at io.vavr.control.Try.of(Try.java:75)
	at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.main(AwsGreengrassProvisioner.java:31)`

Note: I have valid AWS credentials available locally (2 AWS accounts). Also although the script failed the EC2 instance was active and it was not terminated (without any warning message). So, I had to terminate it manually. Last, unless specifically required I think instantiating a free tier EC2 instance (e.g.  t2.micro) would be preferable

**Comment by timmattison** [comment]
I've seen this happen when there's too long of a delay before the instance launches. I've also seen in happen if it tries to use the wrong SSH key.

If you think that this case was not one of those please re-open it and let's dig in.
