### ISSUE TITLE
How to attach an existing local resource to lambda?

### ISSUE THREAD

**Issue by yunchancho** [awslabs/aws-greengrass-provisioner#448]
Hi, 

I don't know how to attach an existing local resource to greengrass lambda through configuration of GGP.

When a local resource to be shared in several lambdas is defined in function.defaults.conf like this, error regarding duplication occurs.

$ ./ggp.sh -a X86_64 -g ggptest -d deployments/origins.conf

- function.defaults.conf
```
conf {
  ...
  localDeviceResources = []
  localVolumeResources = [
    {
      name="test-storage"
      sourcePath = "/test"
      destinationPath = "/test" 
      readWrite = true
    }
  ]
  ... 
```

- origins.conf
```
conf {
  functions = [
    "testFunction1",
    "testFunction2"
  ]
}
```

- console log
```
[INFO] BasicDeploymentHelper: Creating resource definition
[ERROR] BasicGreengrassHelper: Duplicate local volume resource source paths defined ["/test"].  Greengrass will not accept this configuration.
[ERROR] AwsGreengrassProvisioner: Invalid resource configuration
java.lang.RuntimeException: Invalid resource configuration
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicGreengrassHelper.disallowDuplicateLocalVolumeSourcePaths(BasicGreengrassHelper.java:940)
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicGreengrassHelper.validateResourceDefinitionVersion(BasicGreengrassHelper.java:869)
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicGreengrassHelper.createResourceDefinitionVersion(BasicGreengrassHelper.java:710)
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicDeploymentHelper.execute(BasicDeploymentHelper.java:689)
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicDeploymentHelper.execute(BasicDeploymentHelper.java:58)
        at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.executeOrDisplayHelp(Operation.java:33)
        at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.lambda$execute$1(Operation.java:21)
        at io.vavr.control.Try.onSuccess(Try.java:712)
        at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.execute(Operation.java:21)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$null$2(AwsGreengrassProvisioner.java:91)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$run$da6d192b$1(AwsGreengrassProvisioner.java:91)
        at io.vavr.control.Try.of(Try.java:75)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.run(AwsGreengrassProvisioner.java:86)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.runProvisioner(AwsGreengrassProvisioner.java:64)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$main$249538b4$1(AwsGreengrassProvisioner.java:32)
        at io.vavr.control.Try.of(Try.java:75)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.main(AwsGreengrassProvisioner.java:32)
[ERROR] AwsGreengrassProvisioner: Invalid resource configuration
```

Could you let me know how to attach one resource to several lambdas?

**Comment by timmattison** [comment]
The configuration for the local resource needs to be moved to the function.conf for the function that needs access to it. If the value is in the defaults it gets applied to all functions. The CDDSensehatJava example has a reference to /dev/fb1 that should help.

Admittedly the inclusion of those values in the defaults file is a bit confusing. I’ll see if that can be updated. It’s basically a convenient way to make sure the value doesn’t show up as missing and throw an exception but obviously makes it less clear where to put it.

**Comment by timmattison** [comment]
This is the link to the config file I mentioned


https://github.com/aws-samples/aws-greengrass-lambda-functions/blob/c6c0db9aa6477fa354067cabd6a053a20c07ea25/functions/CDDSenseHatJava/function.conf#L14

**Comment by yunchancho** [comment]
@timmattison After removing localVolumeResources from `function.defaults.conf`, I did as you said. However same error still occurs.

- function.conf in testFunction1 directory
```
conf {
  language = "PYTHON3_7"
  functionName = "testFunction1"
  localVolumeResources = [
    {
      name="test-storage"
      sourcePath = "/test"
      destinationPath = "/test" 
      readWrite = true
    }
  ]
 ...
}
```

- function.conf in testFunction2 directory
```
conf {
  language = "PYTHON3_7"
  functionName = "testFunction2"
  localVolumeResources = [
    {
      name="test-storage"
      sourcePath = "/test"
      destinationPath = "/test" 
      readWrite = true
    }
  ]
 ...
}
```

When I try to define local device(e.g. /dev/fb1) to each function.conf as link which you mentioned, completely same error occurs.

```
[INFO] BasicDeploymentHelper: Creating resource definition
[ERROR] BasicGreengrassHelper: Duplicate local device resource source paths defined ["/dev/fb1"].  Greengrass will not accept this configuration.
[ERROR] AwsGreengrassProvisioner: Invalid resource configuration
java.lang.RuntimeException: Invalid resource configuration
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicGreengrassHelper.disallowDuplicateLocalDeviceSourcePaths(BasicGreengrassHelper.java:923)
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicGreengrassHelper.validateResourceDefinitionVersion(BasicGreengrassHelper.java:862)
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicGreengrassHelper.createResourceDefinitionVersion(BasicGreengrassHelper.java:710)
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicDeploymentHelper.execute(BasicDeploymentHelper.java:689)
        at com.awslabs.aws.greengrass.provisioner.implementations.helpers.BasicDeploymentHelper.execute(BasicDeploymentHelper.java:58)
        at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.executeOrDisplayHelp(Operation.java:33)
        at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.lambda$execute$1(Operation.java:21)
        at io.vavr.control.Try.onSuccess(Try.java:712)
        at com.awslabs.aws.greengrass.provisioner.interfaces.helpers.Operation.execute(Operation.java:21)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$null$2(AwsGreengrassProvisioner.java:91)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$run$da6d192b$1(AwsGreengrassProvisioner.java:91)
        at io.vavr.control.Try.of(Try.java:75)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.run(AwsGreengrassProvisioner.java:86)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.runProvisioner(AwsGreengrassProvisioner.java:64)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.lambda$main$249538b4$1(AwsGreengrassProvisioner.java:32)
        at io.vavr.control.Try.of(Try.java:75)
        at com.awslabs.aws.greengrass.provisioner.AwsGreengrassProvisioner.main(AwsGreengrassProvisioner.java:32)
[ERROR] AwsGreengrassProvisioner: Invalid resource configuration
```

**Comment by timmattison** [comment]
I wouldn’t suggest you remove the blank entry from the defaults file. That will currently cause issues. But today you cannot have a local resource shared between two functions.

Are you using it as a mechanism to pass data between the two functions? Or do both functions need to monitor the same local resource? I can explain alternate ways to achieve both.

**Comment by timmattison** [comment]
Also, you can omit the name field as it will be auto generated for you. If in another process you need to know this name ahead of time though setting it in the config file is your best bet.

**Comment by yunchancho** [comment]
I didn't remove blank entry from defaults file due to deploy error. And I tried to omit name field in each function conf, or set other value to name field. However error still occured.

Both functions need to read or write same local directory in my case. Do you let me know alternative way for this?

**Comment by timmattison** [comment]
Double checking if Greengrass supports this now. It used to not support it so I added a check to avoid it.

**Comment by timmattison** [comment]
I just removed my checks for this and when I create a configuration with overlapping resources it returns this error message:

```
Resource's source or destination path is used by existing resource
```

**Comment by timmattison** [comment]
And this happens for read/write and read-only permissions

**Comment by timmattison** [comment]
Generally if you want to share resources I'd suggest you have a single function that has access to those resources and creates a simple API to provide access to them. In this case a local invoke would probably work the best. I may be able to create an example function and deployment that demonstrates that. Would that help?

**Comment by yunchancho** [comment]
> Double checking if Greengrass supports this now. It used to not support it so I added a check to avoid it.

https://docs.aws.amazon.com/greengrass/latest/developerguide/lra-console.html#lra-console-create-resource

First we can create a local resource on the Aws Management Console, and then attach the local resource to existing lambdas. I checked this works well on the Aws Management Console. 

Is the feature not supported yet in current GGP?

**Comment by timmattison** [comment]
Did you successfully deploy that configuration? I can create that configuration but the deployment fails with the error that I posted.

**Comment by yunchancho** [comment]
Yes, I deployed that configuration to my greengrass device successfully. Did you create a directory or file of source path in your device and allow proper permissions(e.g. 0777) to it?

**Comment by timmattison** [comment]
I think I may know a way to fix this. I’ll investigate on Monday as well. If Greengrass supports this now the issue could be that my automatically generated name is the same.

If I can’t get it working I may need to get a copy of your group’s resource definition so I can adjust the code to build it the same way. The AWS-IoT-client project on Github has a command “greengrass-get-latest-resource-definition” that can dump it as JSON.

**Comment by yunchancho** [comment]
Surely, AWS Greengrass doesn't allow existing local resource to be recreated. But it allows several lambdas to refer to the existing local resource. 

Thanks for your investigation. When you need to my test group's resource definition, please let me know.

**Comment by timmattison** [comment]
I have an idea of how to resolve this. I'll work on it after the top-level directory issue you reported is fixed.

**Comment by timmattison** [comment]
I haven't forgotten about this. I'm in the middle of trying to finish up connector support. Once that's done I can get back to this.

**Comment by timmattison** [comment]
Back on this today and tomorrow.

**Comment by timmattison** [comment]
I'm restructuring things to make this easier to implement a bit. Hopefully it won't take long. The high level plan is this.

1) Scan the device and volume resources across all functions and determine if there are any duplicates
2) If there are duplicates we'll clear out any names/IDs for the resource that the user has defined (we need to be sure the resource name is the same for all functions), automatically generate one, and then re-assign that name/ID to each function that uses it.

The resources are created independent of the functions. Functions simply get a resource access policy for a named resource. If all goes well I'll get this in today and write a sample config that proves it works.

**Comment by yunchancho** [comment]
That's exactly what I expect to be implemented! One thing that we have to consider about volume resource is that resource name/ID and source path must be unique, but duplicated destination path is permitted by AWS Greengrass.

**Comment by timmattison** [comment]
Good points. I'll make sure I check the source path only.

**Comment by timmattison** [comment]
I've done a lot on this and so far I have duplicate device resources working, and duplicate identical volume resources working. But I've hit a snag where if I have a volume resource whose source is "/tmp" and destination is "/tempdir2" and a separate volume resource whose source is also "/tmp" but whose destination is "/tempdir3" the Greengrass cloud service returns this error:

```
Resource's source or destination path is used by existing resource.
```

These resources are used in two separate functions so it's not that a single function can't have both. There's some limit to reusing source and/or destination path that I need to get right.

**Comment by yunchancho** [comment]
Yes. Several days ago I had also checked that same value as source path of volume resource is not permitted by Greengrass cloud service. Once we follow this rule, we can configure all created resources to a function.

**Comment by timmattison** [comment]
I’ll write some tests to verify the behavior and then implement it that way. Shouldn’t take too long.

**Comment by timmattison** [comment]
Tests look good. Now I have a way to validate what I'm implementing. I'm traveling this week but will do my best to get this in in the next few days.

**Comment by yunchancho** [comment]
Great! If you share your result later, I also test it on my dev environment. Hope to enjoy your trip 😄

**Comment by timmattison** [comment]
Sorry. After the weekend. Travel took the whole day today.

**Comment by timmattison** [comment]
Back on it today. Being overly careful to try to make sure we don't need to revisit this. There are some edge cases I'm working to sort out.

**Comment by timmattison** [comment]
Expect a release in a few hours at most. Just running the tests and debugging some minor environmental issues.

**Comment by timmattison** [comment]
Commits pushed, running final tests.

**Comment by timmattison** [comment]
OK, it's done! @yunchancho let me know if this works for you or not. If not, just re-open it and we'll touch it up.

**Comment by yunchancho** [comment]
@timmattison Thanks for your works!! Great!! Could you let me know how to configure local resources in *.conf to test and use your implementation?

**Comment by timmattison** [comment]
Check out the python3-shared-file.conf deployment. It references SharedFile1Python3 and SharedFile2Python3. They have a volume resource that they share and use two files to communicate between each other (one writes in file X and the other reads file X, one writes in file Y and the other reads file Y).

Let me know if that helps.

**Comment by yunchancho** [comment]
@timmattison Perfect! Thanks for your works 👍
